# Project Euler Challenge 2
#!/usr/bin/env python3

def sum_even_fib(n):
    """"
    Return the sum of all even Fibonacci terms less than n.

    A Fibonacci sequence is generated by adding the previous 2 terms:
    1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

    The even Fibonacci sequence starting from zero is:
    0, 2, 8, 34, 144, 610, ...
    where G[n] = 4*G[n-2] + G[n-1].

    Example:
    >>> sum_even_fib(4000000)
    4613732


    x, y, sum = 0, 2, 0

    while y < n:
        x, y, sum = y, 4 * y + x, sum + y

    return sum


t = int(input())
for _ in range(t):
    n = int(input())
    print(sum_even_fib(n))
